website/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='gttour/')),
    path('admin/', admin.site.urls),
    path('gttour/', include('gttour.urls')),
    path('survey/', include('survey.urls')),
    path('waitting/',  include('waitting.urls')),
    path('classification/', include('classification.urls')),
    path('tourlist/', include('tourlist.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/tourlist/urls.py
from django.urls import path

from . import views

app_name = 'tourlist'

urlpatterns = [
    # path('', views.index, name='index1'),
    path('similadest_view/', views.similadest_view, name='similadest_view'),
    path('destination_view/', views.destination_view, name='destination_view'),
    path('surveydest_view/', views.surveydest_view, name='surveydest_view'),

    path('similadest_view/list1/', views.simlist1, name='simlist1'),
    path('similadest_view/list2/', views.simlist2, name='simlist2'),
    path('similadest_view/list3/', views.simlist3, name='simlist3'),
    path('similadest_view/list4/', views.simlist4, name='simlist4'),
    path('similadest_view/list5/', views.simlist5, name='simlist5'),

    path('destination_view/list1/', views.deslist1, name='deslist1'),
    path('destination_view/list2/', views.deslist2, name='deslist2'),
    path('destination_view/list3/', views.deslist3, name='deslist3'),
    path('destination_view/list4/', views.deslist4, name='deslist4'),
    path('destination_view/list5/', views.deslist5, name='deslist5'),

    path('surveydest_view/list1/', views.surveylist1, name='surveylist1'),
    path('surveydest_view/list2/', views.surveylist2, name='surveylist2'),
    path('surveydest_view/list3/', views.surveylist3, name='surveylist3'),
    # 상세정보 url 필요할듯
]

website/tourlist/models.py
from django.db import models
from django.conf import settings

class Tourmodel(models.Model):
    location = models.CharField(max_length=200)
    location_code = models.CharField(max_length=5)
    positive = models.TextField()
    negative = models.TextField()
    image = models.ImageField()
    tour_loc_1 = models.TextField()
    tour_loc_2 = models.TextField()
    tour_loc_3 = models.TextField()
    def __str__(self):                 
        return f"{self.location}, {self.location_code}, {self.positive}, {self.negative}, {self.tour_loc_1},{self.tour_loc_2},{self.tour_loc_3}"

website/tourlist/views.py
from django.shortcuts import render
from .models import Tourmodel
import json
from django.http import JsonResponse

# def read_json_file(file_path):
#     with open(file_path, 'r', encoding='utf-8') as file:
#         data = json.load(file)
#     return data


def surveydest_view(request):
    with open('./survey_data.json', 'r', encoding='utf-8') as json_file:
        survey_data_data = json.load(json_file)    
   
    survey_data_list = []  

    for location in [survey_data_data['myarea_1'], survey_data_data['myarea_2'], survey_data_data['myarea_3']]:
        try:
            db_object = Tourmodel.objects.get(location=location)
            survey_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('survey_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(survey_data_list, json_file)
 
    return render(request, 'tourlist/surveydest.html', {'survey_data_list': survey_data_list})



def similadest_view(request):
    with open('./similadest.json', 'r', encoding='utf-8') as json_file:
        similadest_data = json.load(json_file)

    location_s = similadest_data['place_location']  
    similadest_data_list = []  

    # try:
    for location in location_s:
        try:
            db_object = Tourmodel.objects.get(location=location)
            similadest_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('similadest_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(similadest_data_list, json_file)
    # print('6',similadest_data_list)
    return render(request, 'tourlist/similadest.html', {'similadest_data_list': similadest_data_list})


def destination_view(request):
    with open('./destination.json', 'r', encoding='utf-8') as json_file:
        destination_data = json.load(json_file)
        
    destination_data_list = []  

    for area in destination_data:  
        try:
            db_object = Tourmodel.objects.get(location=area)
            destination_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative' : db_object.negative,
                'image': db_object.image.url, 
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('destination_data_list.json', 'w') as json_file:
        json.dump(destination_data_list, json_file)
    # print('7',destination_data_list)
    return render(request, 'tourlist/destination.html', {'destination_data_list': destination_data_list})

def surveylist1(request):
    with open('./survey_data.json', 'r', encoding='utf-8') as json_file:
        survey_data_data = json.load(json_file)    
   
    survey_data_list = []  

    for location in [survey_data_data['myarea_1'], survey_data_data['myarea_2'], survey_data_data['myarea_3']]:
        try:
            db_object = Tourmodel.objects.get(location=location)
            survey_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('survey_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(survey_data_list, json_file)
 
    return render(request, 'tourlist/surveylist1.html', {'survey_data_list': survey_data_list})

def surveylist2(request):
    with open('./survey_data.json', 'r', encoding='utf-8') as json_file:
        survey_data_data = json.load(json_file)    
   
    survey_data_list = []  

    for location in [survey_data_data['myarea_1'], survey_data_data['myarea_2'], survey_data_data['myarea_3']]:
        try:
            db_object = Tourmodel.objects.get(location=location)
            survey_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('survey_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(survey_data_list, json_file)
 
    return render(request, 'tourlist/surveylist2.html', {'survey_data_list': survey_data_list})

def surveylist3(request):
    with open('./survey_data.json', 'r', encoding='utf-8') as json_file:
        survey_data_data = json.load(json_file)    
   
    survey_data_list = []  

    for location in [survey_data_data['myarea_1'], survey_data_data['myarea_2'], survey_data_data['myarea_3']]:
        try:
            db_object = Tourmodel.objects.get(location=location)
            survey_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('survey_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(survey_data_list, json_file)
 
    return render(request, 'tourlist/surveylist3.html', {'survey_data_list': survey_data_list})

def simlist1(request):
    with open('./similadest.json', 'r', encoding='utf-8') as json_file:
        similadest_data = json.load(json_file)

    location_s = similadest_data['place_location']  
    similadest_data_list = []  

    # try:
    for location in location_s:
        try:
            db_object = Tourmodel.objects.get(location=location)
            similadest_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('similadest_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(similadest_data_list, json_file)

    return render(request, 'tourlist/simlist1.html', {'similadest_data_list': similadest_data_list})

def simlist2(request):
    with open('./similadest.json', 'r', encoding='utf-8') as json_file:
        similadest_data = json.load(json_file)

    location_s = similadest_data['place_location']  
    similadest_data_list = []  

    # try:
    for location in location_s:
        try:
            db_object = Tourmodel.objects.get(location=location)
            similadest_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('similadest_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(similadest_data_list, json_file)

    return render(request, 'tourlist/simlist2.html', {'similadest_data_list': similadest_data_list})

def simlist3(request):
    with open('./similadest.json', 'r', encoding='utf-8') as json_file:
        similadest_data = json.load(json_file)

    location_s = similadest_data['place_location']  
    similadest_data_list = []  

    # try:
    for location in location_s:
        try:
            db_object = Tourmodel.objects.get(location=location)
            similadest_data_list.append({
                'location': db_object.location,
                'positive': db_object.positive,
                'negative': db_object.negative,
                'image': db_object.image.url,
                'tour_loc_1': db_object.tour_loc_1,
                'tour_loc_2': db_object.tour_loc_2,
                'tour_loc_3': db_object.tour_loc_3,
            })
        except Tourmodel.DoesNotExist:
            pass
        
    with open('similadest_data_list.json', 'w', encoding='utf-8') as json_file:
        json.dump(similadest_data_list, json_file)

    return render(request, 'tourlist/simlist3.html', {'similadest_data_list': similadest_data_list})

def simlist4(request):
    with open('./similadest.json', 'r', encoding='utf-8') as json_file:
        similadest_data = json.load(json_file)

    location_s = similadest_data['place_location']  

website/templates/tourlist/deslist2.html
{% extends 'base.html' %}
{% block content %}
<meta charset="UTF-8">
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 60px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }
</style>

<div class="main">
    <div class="hero">
        <h4 style="font-family: font1; font-size: 35px;">다음 목록은 {{ destination_data_list.1.location }} 여행 정보에요</h4><br>
    
        <div style="width:1000px; height:500px; border:1px solid skyblue; border-radius: 20px; float:right; margin-right:20px;">
            <div id="imageContainer" style="width:625px; height:500px; border-right:1px solid skyblue; float:left; margin-right:20px; font-family: font1;">
                <h3 style="font-size: 22px;"><키워드맵></h3>
                {% if destination_data_list.1.image %}
                    <img src="{{ destination_data_list.1.image }}" alt="{{ destination_data_list.1.location }}" style="max-width: 625px; max-height: 450px; border-radius: 20px;">
                {% else %}
                    <p>No image</p>
                {% endif %}
            </div>

            <div id="tourLocContainer" style="font-family: font1; font-size: 10px;">
                <br><h3 style="font-size: 22px;"><주요 관광지></h3>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.1.tour_loc_1 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.1.tour_loc_1 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.1.tour_loc_2 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.1.tour_loc_2 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.1.tour_loc_3 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.1.tour_loc_3 }}</b></a></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><긍정></h3>
                <p><b>{{ destination_data_list.1.positive }}</b></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><부정></h3>
                <p><b>{{ destination_data_list.1.negative }}</b></p>
            </div>
    </div>
</div>
{% endblock %}

website/templates/tourlist/deslist3.html
{% extends 'base.html' %}
{% block content %}
<meta charset="UTF-8">
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 60px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }
</style>

<div class="main">
    <div class="hero">
        <h4 style="font-family: font1; font-size: 35px;">다음 목록은 {{ destination_data_list.2.location }} 여행 정보에요</h4><br>
    
        <div style="width:1000px; height:500px; border:1px solid skyblue; border-radius: 20px; float:right; margin-right:20px;">
            <div id="imageContainer" style="width:625px; height:500px; border-right:1px solid skyblue; float:left; margin-right:20px; font-family: font1;">
                <h3 style="font-size: 22px;"><키워드맵></h3>
                {% if destination_data_list.2.image %}
                    <img src="{{ destination_data_list.2.image }}" alt="{{ destination_data_list.2.location }}" style="max-width: 625px; max-height: 450px; border-radius: 20px;">
                {% else %}
                    <p>No image</p>
                {% endif %}
            </div>

            <div id="tourLocContainer" style="font-family: font1; font-size: 10px;">
                <br><h3 style="font-size: 22px;"><주요 관광지></h3>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.2.tour_loc_1 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.2.tour_loc_1 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.2.tour_loc_2 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.2.tour_loc_2 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.2.tour_loc_3 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.2.tour_loc_3 }}</b></a></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><긍정></h3>
                <p><b>{{ destination_data_list.2.positive }}</b></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><부정></h3>
                <p><b>{{ destination_data_list.2.negative }}</b></p>
            </div>
    </div>
</div>
{% endblock %}

website/templates/tourlist/deslist4.html
{% extends 'base.html' %}
{% block content %}
<meta charset="UTF-8">
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 60px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }
</style>

<div class="main">
    <div class="hero">
        <h4 style="font-family: font1; font-size: 35px;">다음 목록은 {{ destination_data_list.3.location }} 여행 정보에요</h4><br>
    
        <div style="width:1000px; height:500px; border:1px solid skyblue; border-radius: 20px; float:right; margin-right:20px;">
            <div id="imageContainer" style="width:625px; height:500px; border-right:1px solid skyblue; float:left; margin-right:20px; font-family: font1;">
                <h3 style="font-size: 22px;"><키워드맵></h3>
                {% if destination_data_list.3.image %}
                    <img src="{{ destination_data_list.3.image }}" alt="{{ destination_data_list.3.location }}" style="max-width: 625px; max-height: 450px; border-radius: 20px;">
                {% else %}
                    <p>No image</p>
                {% endif %}
            </div>

            <div id="tourLocContainer" style="font-family: font1; font-size: 10px;">
                <br><h3 style="font-size: 22px;"><주요 관광지></h3>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.3.tour_loc_1 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.3.tour_loc_1 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.3.tour_loc_2 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.3.tour_loc_2 }}</b></a></p>
                <p><a href="https://search.naver.com/search.naver?query={{ destination_data_list.3.tour_loc_3 }}" target="_blank" style="text-decoration: none; color: skyblue"><b>{{ destination_data_list.3.tour_loc_3 }}</b></a></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><긍정></h3>
                <p><b>{{ destination_data_list.3.positive }}</b></p>
                <br>
                <br>
                <h3 style="font-size: 22px;"><부정></h3>
                <p><b>{{ destination_data_list.3.negative }}</b></p>
            </div>
    </div>
</div>
{% endblock %}

website/templates/tourlist/destination.html
{% extends 'base.html' %}
{% block content %}
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 45px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }

    .main .hero button{
        background: none;
        border: 2px solid skyblue;
        color: black;
        padding: 15px 20px;
        border-radius: 20px;
        margin-top: 30px;
        outline: none;
        cursor: pointer;
        transition: all .4s;
    }

    .main .hero button:hover{
        background-color: skyblue;
        box-shadow: 3px 2px 5px 1px rgb(0 0 0 / 20%);
    }
    
    .link {
        color: black;
        font-size: 1.2em;
        padding: 0.3em 0.5em;
        margin-right: 0.1em;
        font-family: 'font1';
        text-decoration: none;
    }

    .link:hover {
        color: skyblue;
    }

</style>

<meta charset="UTF-8">
<div class="main">
    <div class="hero" style="width:1000px; height:500px">
        <h2 style="font-family: font1;">다음 목록은 유사 장소 기반 추천 여행지에요</h2>
        <h6 style="font-family: font1; font-size: 20px;">지역을 선택하세요!</h6><br>
        <div style="display: flex; font-size: 4px;">
            <a href="{% url 'tourlist:deslist1' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ destination_data_list.0.location }}</h5></button></a>
            <a href="{% url 'tourlist:deslist2' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ destination_data_list.1.location }}</h5></button></a>
            <a href="{% url 'tourlist:deslist3' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ destination_data_list.2.location }}</h5></button></a>
            <a href="{% url 'tourlist:deslist4' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ destination_data_list.3.location }}</h5></button></a>
            <a href="{% url 'tourlist:deslist5' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ destination_data_list.4.location }}</h5></button></a>
        </div>
    </div>
</div>
{% endblock %}

website/templates/tourlist/similadest.html
{% extends 'base.html' %}
{% block content %}
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 45px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }

    .main .hero button{
        background: none;
        border: 2px solid skyblue;
        color: black;
        padding: 15px 20px;
        border-radius: 20px;
        margin-top: 30px;
        display: inline-block;
        outline: none;
        cursor: pointer;
        transition: all .4s;
    }

    .main .hero button:hover{
        background-color: skyblue;
        box-shadow: 3px 2px 5px 1px rgb(0 0 0 / 20%);
    }
    
    .link {
        color: black;
        font-size: 1.2em;
        padding: 0.3em 0.5em;
        margin-right: 0.1em;
        font-family: 'font1';
        text-decoration: none;
    }

    .link:hover {
        color: skyblue;
    }
</style>

<meta charset="UTF-8">
<div class="main">
    <div class="hero" style="width:1000px; height:500px">
        <h2 style="font-family: font1;">다음 목록은 유사 집단 기반 추천 여행지에요</h2>
        <h6 style="font-family: font1; font-size: 20px;">지역을 선택하세요!</h6><br>
        <div style="display: flex; font-size: 1px;">
            <a href="{% url 'tourlist:simlist1' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ similadest_data_list.0.location }}</h5></button></a>
            <a href="{% url 'tourlist:simlist2' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ similadest_data_list.1.location }}</h5></button></a>
            <a href="{% url 'tourlist:simlist3' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ similadest_data_list.2.location }}</h5></button></a>
            <a href="{% url 'tourlist:simlist4' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ similadest_data_list.3.location }}</h5></button></a>
            <a href="{% url 'tourlist:simlist5' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ similadest_data_list.4.location }}</h5></button></a>
        </div>
    </div>
</div>
{% endblock %}

website/templates/tourlist/surveydest.html
{% extends 'base.html' %}
{% block content %}
<style>
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 45px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }

    .main .hero button{
        background: none;
        border: 2px solid skyblue;
        color: black;
        padding: 15px 20px;
        border-radius: 20px;
        margin-top: 30px;
        display: inline-block;
        outline: none;
        cursor: pointer;
        transition: all .4s;
    }

    .main .hero button:hover{
        background-color: skyblue;
        box-shadow: 3px 2px 5px 1px rgb(0 0 0 / 20%);
    }
    
    .link {
        color: black;
        font-size: 1.2em;
        padding: 0.3em 0.5em;
        margin-right: 0.1em;
        font-family: 'font1';
        text-decoration: none;
    }

    .link:hover {
        color: skyblue;
    }

</style>

<meta charset="UTF-8">
<div class="main">
    <div class="hero" style="width:1000px; height:500px">
        <h2 style="font-family: font1;">다음 목록은 설문조사에서 선택한 관심지역이에요!</h2>
        <h6 style="font-family: font1; font-size: 20px;">지역을 선택하세요!</h6><br>
        <div style="display: flex; font-size: 4px;">
            <a href="{% url 'tourlist:surveylist1' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ survey_data_list.0.location }}</h5></button></a>
            <a href="{% url 'tourlist:surveylist2' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ survey_data_list.1.location }}</h5></button></a>
            <a href="{% url 'tourlist:surveylist3' %}" class="link"><button type="submit" style="font-family: font3;"><h5>{{ survey_data_list.2.location }}</h5></button></a>
        </div>
    </div>
</div>
{% endblock %}