website/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='gttour/')),
    path('admin/', admin.site.urls),
    path('gttour/', include('gttour.urls')),
    path('survey/', include('survey.urls')),
    path('waitting/',  include('waitting.urls')),
    path('classification/', include('classification.urls')),
    path('tourlist/', include('tourlist.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/gttour/urls.py
from django.urls import path

from . import views

app_name = 'gttour'

urlpatterns = [
    path('', views.index, name='index'),
]

website/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- gttour CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>3조 투어</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

website/templates/navbar.html
<!-- 네비게이션바 -->
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom"> -->
<style>
    .navbar-toggler{
        background: none;
        border: 2px solid #e3f2fd;
        color: black;
        padding: 10px 10px;
        border-radius: 20px;
        margin-top: 0px;
        outline: none;
        cursor: pointer;
        transition: all .4s;
    }

    .navbar-toggler:hover{
        background-color: #e3f2fd;
    }

        .top{
            font-size: 25px;
            font-family: "font2"
        }
</style>

<nav class="navbar navbar-light" style="background-color: skyblue; box-shadow: 3px 4px 5px 2px rgb(0 0 0 / 20%); ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'gttour:index' %}">
            <span class ="top">🧭3조 투어</span>
        </a>
            <div class="navbar-toggler" type="button" style="background-color: #e3f2fd; box-shadow: 3px 3px 5px 1px rgb(0 0 0 / 20%);">
                <button style="background-color: #e3f2fd; border:1px solid #e3f2fd;" onclick="history.back()">&#9194;</button>
                <button style="background-color: #e3f2fd; border:1px solid #e3f2fd;" onclick="history.forward()">&#9193;</button>
            </div>
        </div>
    </div>
</nav>