website/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='gttour/')),
    path('admin/', admin.site.urls),
    path('gttour/', include('gttour.urls')),
    path('survey/', include('survey.urls')),
    path('waitting/',  include('waitting.urls')),
    path('classification/', include('classification.urls')),
    path('tourlist/', include('tourlist.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/gttour/urls.py
from django.urls import path

from . import views

app_name = 'gttour'

urlpatterns = [
    path('', views.index, name='index'),
]

website/survey/urls.py
from django.urls import path

from . import views

app_name = 'survey'

urlpatterns = [
    path('', views.index, name='index'),
]

website/gttour/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

website/gttour/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect

def index(request):
    return render(request, 'gttour/gttour.html')

website/templates/gttour/gttour.html
{% extends 'base.html' %}
{% block content %}
<style>
    
    html, body {
        margin: 0;
    }

    .main{
        width: 100%;
        height: 100vh;
        margin: 0 auto;
        background: #e3f2fd;
        padding: 0;
        margin: 0;
    }

    .main .hero{
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    .main .hero h2{
        font-size: 70px;
        margin-bottom: 20px;
    }

    .main .hero p{
        font-size: 25px;
    }

    .main .hero button{
        background: none;
        border: 2px solid skyblue;
        color: black;
        padding: 15px 20px;
        border-radius: 20px;
        margin-top: 30px;
        outline: none;
        cursor: pointer;
        transition: all .4s;
        
    }

    .main .hero button:hover{
        background-color: skyblue;
        box-shadow: 3px 2px 5px 1px rgb(0 0 0 / 20%);
    }
</style>

<div class="main">
    <div class="hero">
        <h2 style="font-family: font1;">여행지 추천 서비스</h2>
        <p style="font-family: font2">🧭3조 투어</p>
        <a href="{% url 'survey:index' %}" style="font-family: font3;"><button>시작하기!</button></a>
    </div>    
</div>
{% endblock %}




<!-- <div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'gttour:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div> -->


<!-- {% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'gttour:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %} -->